Implement test suite
ocharles/weeder pull request #116
Opened 2023-06-01 15:17 UTC by ryndubei

8f2d91e8ddf89bae9556cc9d1e0a6ab8ed0fe3a8 implements a test suite which can be run with `cabal test`. At the moment, there are 3 tests, of which 2 (`NumInstance` and `DeriveGeneric`) are supposed to fail at the moment, in preparation for adding support for type class instances to Weeder.

A test `ExampleTest` can be easily added by creating `ExampleTest.stdout`, `ExampleTest.dhall` and a directory `ExampleTest` in `test/Spec` containing the modules to be compiled to `hie` files, and specifying the modules in `weeder.cabal`.

The rest of the commits allow the test suite to export the dependency graph of each test to a dotfile, and to convert those dotfiles to PNG images with GraphViz when given the `--graphviz` flag, for example as `cabal test --test-option=--graphviz`, for easier debugging.

![Graph of BasicExample.hs](https://github.com/ocharles/weeder/assets/114586905/2139bf64-19c4-4f29-9cef-a15d3a1eb8b8)

2023-06-22 14:45 UTC, ryndubei commented
Test suite converted to `toml` and failing tests removed for now, should be good to be merged.

2023-06-23 10:47 UTC, ocharles requested changes

2023-06-23 10:47 UTC, ocharles commented on src/Weeder/Main.hs
> +mainWithConfig' hieExt hieDirectories requireHsFiles Config{ rootPatterns, typeClassRoots } = do
I'm not very big on `'` naming, and we now end up with three `main*` functions. This seems a bit confusing. How about we go with just having `mainWithConfig` return `(ExitCode, Analysis)`. Then `main` can be responsible for calling `exitWith`, and your test suite can check `ExitCode` too.

So to recap:

* `main` calls `mainWithConfig` and then calls `exitWith` with the `ExitCode` that `mainWithConfig` returns
* `mainWithConfig` reurns `(ExitCode, Analysis)`. The `ExitCode` is formatted based on `null warnings`, as before.
* We drop the new `mainWithConfig'`.

2023-06-23 18:51 UTC, ocharles commented
LGTM!

2023-06-23 20:15 UTC, ryndubei commented
Should I merge this then?

2023-06-23 20:50 UTC, ocharles commented
Yep, go ahead

2023-06-23 20:54 UTC, merged