Update README.md
ocharles/weeder pull request #131
Opened 2023-07-11 08:57 UTC by ocharles

2023-07-11 15:28 UTC, ryndubei requested changes

2023-07-11 15:28 UTC, ryndubei commented on README.md
```suggestion

You can add instances of specific type classes as roots with the `root-classes` field, or toggle whether Weeder considers all type class instances as roots with the `type-class-roots` configuration option.
```

2023-07-11 15:28 UTC, ryndubei commented on README.md
We should also mention `root-classes` and `root-instances` under the "Calling Weeder" heading.

2023-08-05 14:27 UTC, ocharles commented
See #135.

2023-08-05 14:27 UTC, closed without merging