Improve config
ocharles/weeder pull request #133
Opened 2023-07-18 15:19 UTC by ryndubei

This implements two things:

- Optional config file and `--write-default-config` flag. The default configuration used is:

```
roots = ["Main.main","^Paths_.*"]

type-class-roots = false

root-classes = ["IsList","IsString"]

root-instances = []
```

`roots` and `type-class-roots` can now also be omitted like `root-classes` and `root-instances`.

- `root-classes` and `root-instances` can match against modules as such:
```
root-instances = [ { module = "Spec.ConfigInstanceModules.Module1", instance = "Bounded T" }
                 , "Read T" 
                 , { module = "Spec.ConfigInstanceModules.Module3" }
                 ]

root-classes = [ { class = "Enum" }
               , { module = "Spec.ConfigInstanceModules.Module2", class = "Show" } 
               ]
```
Specifying `{ module = ... }` without `class` or `instance` in either `root-classes` or `root-instances` marks all instances in that module as roots. `{ class = "Enum" }` and just `"Enum"` are equivalent.

2023-07-19 09:00 UTC, ocharles requested changes

2023-07-19 12:12 UTC, ryndubei commented on src/Weeder/Config.hs
> +   in TOML.decode cf' == Right cf
Done - I primarily did this in order to be able to get HLS to evaluate `prop_configToToml` even if the other modules don't yet compile, but looks like that still works even if `prop_configToToml` is in the test suite

2023-07-19 14:37 UTC, ocharles approved these changes
This all looks good to me! Thanks for the amendments.

2023-07-20 12:06 UTC, ryndubei commented
Added --no-default-fields flag. This helps avoid unexpected behaviour when new fields are added, but the config file is not changed.

2023-07-20 12:15 UTC, merged